### ISSUE TITLE
When create new enrollment with XXTEST TRACKER RULES program a crash occurred

### ISSUE THREAD

**Issue by xurxodev** [EyeSeeTea/dhis2-android-trackercapture#162]
FATAL EXCEPTION: Thread-207
                                                                                      Process: org.hisp.dhis.android.trackercapture, PID: 13252
                                                                                      java.lang.NullPointerException: Attempt to invoke virtual method 'org.hisp.dhis.android.sdk.utils.api.ValueType org.hisp.dhis.android.sdk.persistence.models.DataElement.getValueType()' on a null object reference
                                                                                          at org.hisp.dhis.android.sdk.utils.services.VariableService.populateDataElementOrAttributeVariable(VariableService.java:635)
                                                                                          at org.hisp.dhis.android.sdk.utils.services.VariableService.populateDataElementAndAttributeVariables(VariableService.java:573)
                                                                                          at org.hisp.dhis.android.sdk.utils.services.VariableService.initProgramRuleVariableMap(VariableService.java:367)
                                                                                          at org.hisp.dhis.android.sdk.utils.services.VariableService.initialize(VariableService.java:183)
                                                                                          at org.hisp.dhis.android.sdk.ui.fragments.common.AbsProgramRuleFragment.evaluateAndApplyProgramRules(AbsProgramRuleFragment.java:86)
                                                                                          at org.hisp.dhis.android.sdk.ui.fragments.eventdataentry.RulesEvaluatorThread.work(RulesEvaluatorThread.java:57)
                                                                                          at org.hisp.dhis.android.sdk.ui.fragments.dataentry.AsyncHelperThread.doWork(AsyncHelperThread.java:48)
                                                                                          at org.hisp.dhis.android.sdk.ui.fragments.dataentry.AsyncHelperThread.run(AsyncHelperThread.java:41)

**Comment by xurxodev** [comment]
the program 'XXTEST Tracker Rules' no longer exists
