### ISSUE TITLE
crashlytics: Validation error dialog 279u

### ISSUE THREAD

**Issue by idelcano** [EyeSeeTea/dhis2-android-trackercapture#252]
Fatal Exception: java.lang.IllegalStateException: Can not perform this action after onSaveInstanceState
       at android.support.v4.app.FragmentManagerImpl.checkStateLoss(FragmentManager.java:1493)
       at android.support.v4.app.FragmentManagerImpl.enqueueAction(FragmentManager.java:1511)
       at android.support.v4.app.BackStackRecord.commitInternal(BackStackRecord.java:638)
       at android.support.v4.app.BackStackRecord.commit(BackStackRecord.java:617)
       at android.support.v4.app.DialogFragment.show(DialogFragment.java:139)
       at org.hisp.dhis.android.sdk.ui.fragments.dataentry.ValidationErrorDialog.show(ValidationErrorDialog.java:116)
       at org.hisp.dhis.android.sdk.ui.fragments.eventdataentry.EventDataEntryRuleHelper.showWarningHiddenValuesDialog(EventDataEntryRuleHelper.java:289)
       at org.hisp.dhis.android.sdk.ui.fragments.common.AbsProgramRuleFragment.evaluateAndApplyProgramRules(AbsProgramRuleFragment.java:122)
       at org.hisp.dhis.android.sdk.ui.fragments.eventdataentry.RulesEvaluatorThread.work(RulesEvaluatorThread.java:57)
       at org.hisp.dhis.android.sdk.ui.fragments.dataentry.AsyncHelperThread.doWork(AsyncHelperThread.java:48)
       at org.hisp.dhis.android.sdk.ui.fragments.dataentry.AsyncHelperThread.run(AsyncHelperThread.java:41)

https://www.fabric.io/dhis2/android/apps/org.hisp.dhis.android.trackercapture/issues/57557ec1ffcdc04250e83369?time=last-ninety-days

1872 CRASHES

279 USERS

**Comment by idelcano** [comment]
To replicate this bug you need add a "Hide field" action in a programrule with a text.

I added a breakpoint here: https://github.com/EyeSeeTea/dhis2-android-sdk/blob/tracker-capture/core/src/main/java/org/hisp/dhis/android/sdk/ui/fragments/common/AbsProgramRuleFragment.java#L99

Other way to test it is create a heavy evaluations of program rules to have time to go back, and when the program rule with the hide field action is active move back.

When the app is evaluating the program rules the hide field action will be display, but if you exit from the program to the dashboard when the program is evaluating the program rules the app will crash.
