### ISSUE TITLE
crashlytics: Enrollment without event causes IndexOutOfBoundsException 45u

### ISSUE THREAD

**Issue by idelcano** [EyeSeeTea/dhis2-android-trackercapture#253]
Caused by java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0
       at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
       at java.util.ArrayList.get(ArrayList.java:308)
       at org.hisp.dhis.android.sdk.utils.services.ProgramIndicatorService.getValue(ProgramIndicatorService.java:448)
       at org.hisp.dhis.android.sdk.utils.services.ProgramIndicatorService.getProgramIndicatorValue(ProgramIndicatorService.java:85)
       at org.hisp.dhis.android.trackercapture.fragments.programoverview.ProgramOverviewFragmentQuery.query(ProgramOverviewFragmentQuery.java:127)
       at org.hisp.dhis.android.trackercapture.fragments.programoverview.ProgramOverviewFragmentQuery.query(ProgramOverviewFragmentQuery.java:58)
       at org.hisp.dhis.android.sdk.persistence.loaders.DbLoader.loadInBackground(DbLoader.java:89)
       at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(AsyncTaskLoader.java:296)
       at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:54)
       at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(AsyncTaskLoader.java:42)
       at android.support.v4.content.ModernAsyncTask$2.call(ModernAsyncTask.java:128)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

See line 80 and 327

date = DateUtils.parseDate(enrollmentProgramInstance.getEvents().get(0).getEventDate());

https://www.fabric.io/dhis2/android/apps/org.hisp.dhis.android.trackercapture/issues/5a560fff8cb3c2fa638edbe4?time=last-ninety-days

1081CRASHES
45 USER

**Comment by idelcano** [comment]
How replicate this bug using  previous2.
In the server:
go to programs->click WHO RMNCH tracker -> view program indicators.
Select "WHO RMNCH ANC Hemoglobin improvement"
Replace expression by: "d2:yearsBetween(V{due_date},V{event_date})" and save.

In the app:
Login and create a WHO RMNCH tracker tei, delete all events and close.
When re-open the tei without programs the app crash.
