### ISSUE TITLE
crashlytics: Null pointer when put trackedEntityInstance 315u

### ISSUE THREAD

**Issue by idelcano** [EyeSeeTea/dhis2-android-trackercapture#254]
Caused by java.lang.NullPointerException: Attempt to invoke interface method 'retrofit.client.Response org.hisp.dhis.android.sdk.network.DhisApi.putTrackedEntityInstance(java.lang.String, org.hisp.dhis.android.sdk.persistence.models.TrackedEntityInstance)' on a null object reference
       at org.hisp.dhis.android.sdk.synchronization.data.trackedentityinstance.TrackedEntityInstanceRemoteDataSource.putTrackedEntityInstance(TrackedEntityInstanceRemoteDataSource.java:59)
       at org.hisp.dhis.android.sdk.synchronization.data.trackedentityinstance.TrackedEntityInstanceRemoteDataSource.save(TrackedEntityInstanceRemoteDataSource.java:37)
       at org.hisp.dhis.android.sdk.synchronization.data.trackedentityinstance.TrackedEntityInstanceRepository.sync(TrackedEntityInstanceRepository.java:32)
       at org.hisp.dhis.android.sdk.synchronization.domain.trackedentityinstance.TrackedEntityInstanceSynchronizer.syncSingleTei(TrackedEntityInstanceSynchronizer.java:81)
       at org.hisp.dhis.android.sdk.synchronization.domain.trackedentityinstance.TrackedEntityInstanceSynchronizer.sync(TrackedEntityInstanceSynchronizer.java:48)
       at org.hisp.dhis.android.sdk.synchronization.domain.trackedentityinstance.SyncTrackedEntityInstanceUseCase.execute(SyncTrackedEntityInstanceUseCase.java:30)
       at org.hisp.dhis.android.trackercapture.fragments.programoverview.ProgramOverviewFragment$11.execute(ProgramOverviewFragment.java:1401)
       at org.hisp.dhis.android.sdk.job.NetworkJob.inBackground(NetworkJob.java:51)
       at org.hisp.dhis.android.sdk.job.NetworkJob.inBackground(NetworkJob.java:38)
       at org.hisp.dhis.android.sdk.job.Job.doInBackground(Job.java:60)
       at org.hisp.dhis.android.sdk.job.Job.doInBackground(Job.java:36)
       at android.os.AsyncTask$2.call(AsyncTask.java:295)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)

I think the problem is put a Tracked entity instance with null UId.

https://www.fabric.io/dhis2/android/apps/org.hisp.dhis.android.trackercapture/issues/5a1eb58061b02d480d82491c?time=last-ninety-days
Crashes 1076
Users 315

**Comment by idelcano** [comment]
this bug(dhisapi is null) is treat in this issue too : https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/255
