### ISSUE TITLE
crashlytics: Null pointer when post trackedEntityInstance with null uid 316u

### ISSUE THREAD

**Issue by idelcano** [EyeSeeTea/dhis2-android-trackercapture#255]
Caused by java.lang.NullPointerException: Attempt to invoke interface method 'retrofit.client.Response org.hisp.dhis.android.sdk.network.DhisApi.postTrackedEntityInstance(org.hisp.dhis.android.sdk.persistence.models.TrackedEntityInstance)' on a null object reference
       at org.hisp.dhis.android.sdk.synchronization.data.trackedentityinstance.TrackedEntityInstanceRemoteDataSource.postTrackedEntityInstance(TrackedEntityInstanceRemoteDataSource.java:54)
       at org.hisp.dhis.android.sdk.synchronization.data.trackedentityinstance.TrackedEntityInstanceRemoteDataSource.save(TrackedEntityInstanceRemoteDataSource.java:35)
       at org.hisp.dhis.android.sdk.synchronization.data.trackedentityinstance.TrackedEntityInstanceRepository.sync(TrackedEntityInstanceRepository.java:32)
       at org.hisp.dhis.android.sdk.synchronization.domain.trackedentityinstance.TrackedEntityInstanceSynchronizer.syncSingleTei(TrackedEntityInstanceSynchronizer.java:81)
       at org.hisp.dhis.android.sdk.synchronization.domain.trackedentityinstance.TrackedEntityInstanceSynchronizer.sync(TrackedEntityInstanceSynchronizer.java:48)
       at org.hisp.dhis.android.sdk.synchronization.domain.trackedentityinstance.SyncTrackedEntityInstanceUseCase.execute(SyncTrackedEntityInstanceUseCase.java:30)
       at org.hisp.dhis.android.trackercapture.fragments.selectprogram.dialogs.ItemStatusDialogFragment$1.execute(ItemStatusDialogFragment.java:125)
       at org.hisp.dhis.android.sdk.job.NetworkJob.inBackground(NetworkJob.java:51)
       at org.hisp.dhis.android.sdk.job.NetworkJob.inBackground(NetworkJob.java:38)
       at org.hisp.dhis.android.sdk.job.Job.doInBackground(Job.java:60)
       at org.hisp.dhis.android.sdk.job.Job.doInBackground(Job.java:36)
       at android.os.AsyncTask$2.call(AsyncTask.java:292)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

https://www.fabric.io/dhis2/android/apps/org.hisp.dhis.android.trackercapture/issues/5a1a955861b02d480d4ba22e?time=last-ninety-days

Related #254
Crashes 763
Users 316

**Comment by idelcano** [comment]
I think this bug is related with null dhisapi and with this other:https://www.fabric.io/dhis2/android/apps/org.hisp.dhis.android.trackercapture/issues/5942120abe077a4dcc255fef?time=last-ninety-days 

https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/18
https://github.com/EyeSeeTea/dhis2-android-trackercapture/issues/34
